---
- name: Install Homebrew packages "{{ item }}"
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ brew_packages }}"
  environment:
    PATH: /home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}
  become: no

- name: Install Homebrew packages "{{ item }}"
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ brew_packages }}"
  environment:
    PATH: /home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}
  become: no
