---
# tasks file for ansible-role-brew
- name: Ensure Homebrew dependencies are installed (Debian/Ubuntu)
  ansible.builtin.package:
    name:
      - build-essential
      - curl
      - file
      - git
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Ensure Homebrew dependencies are installed (Arch Linux)
  ansible.builtin.pacman:
    name:
      - base-devel
      - curl
      - git
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: "{{ homebrew_path }}/bin/brew"
  register: brew_binary

- name: Install Homebrew on Linux
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: true
  when: not brew_binary.stat.exists

- name: Detect user's current shell
  ansible.builtin.shell: "getent passwd {{ ansible_user_id }} | cut -d: -f7"
  register: user_shell
  changed_when: false

- name: Add Homebrew to PATH
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present

- name: Add task to install packages
  ansible.builtin.include_tasks: install-packages.yaml
