---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  #- name: ubuntu_24
  #  image: geerlingguy/docker-ubuntu2004-ansible:latest
  #  command: /lib/systemd/systemd
  #  privileged: true
  #  volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #  cgroupns_mode: host
  #  memory_limit: 512m
  #  cpus: 1.0
  #- name: debian_11
  #  image: geerlingguy/docker-debian11-ansible:latest
  #  command: /lib/systemd/systemd
  #  privileged: true
  #  volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #  cgroupns_mode: host
  #  memory_limit: 512m
  #  cpus: 1.0

  - name: archlinux
    image: archlinux:latest
    command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    memory_limit: 512m
    cpus: 1.0
    # Pre-install Python and other requirements
    pre_build_image: true
    dockerfile: Dockerfile.arch

provisioner:
  name: ansible

verifier:
  name: ansible
