---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: brew-ubuntu_24
    image: ubuntu:24.04
    #command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    memory_limit: 512m
    cpus: 1.0

  - name: brew-debian_12
    image: debian:12.5
    #command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    memory_limit: 512m
    cpus: 1.0

  - name: brew-archlinux
    image: archlinux:latest
    #command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    memory_limit: 512m
    cpus: 1.0
    # Pre-install Python and other requirements
    pre_build_image: true
    dockerfile: Dockerfile.arch
    #environment:
    #  HOME: /home/molecule
provisioner:
  name: ansible

verifier:
  name: ansible
