---
name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - debian:12.6
          - ubuntu:24.04
          - archlinux:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.0
        with:
          image: "${{ matrix.image }}"
          options: parallel
          scenario: default
