---
name: CI

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install molecule
        run: |
          python3 -m pip install --upgrade pip
          pip install molecule
      - name: Run molecule lint
        run: |
          molecule lint

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - debian:12.6
          - ubuntu:24.04
          - archlinux:latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.0
        with:
          image: "${{ matrix.image }}"
          options: parallel
          scenario: default
